### ISSUE TITLE
Support Windows long paths

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/trash#16]
See: https://github.com/sindresorhus/recycle-bin/issues/1

Help wanted :)

**Comment by dhanyn10** [comment]
i'm waiting till this issues fixed. 👍

**Comment by dhanyn10** [comment]
may i know how long the path can be executed normally?

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/trash/commit/8ec326082e3bf02a3598d84da7ed711d8e680a88

**Comment by Baccanno** [comment]
I personally still have the issue with a long path :
Windows UI :
![image](https://user-images.githubusercontent.com/3664080/148547490-57a316d5-d4a2-4308-b67f-c0b84158d0bb.png)
Trash result :
`Error: Command failed: C:\Users\XXXX\AppData\Roaming\npm\node_modules\trash-cli\node_modules\trash\lib\windows-trash.exe `

```
$ trash --version
5.0.0
```
